### PR TITLE
Fix Typo LANGUAGE_FIELD->LANGUAGE in SerializeIndex

### PR DESCRIPTION
**Pull request by ahmedisam99**
Fix typo/bug in index serialization and creation which serializes `LanguageField` to `Language` instead of `Language_Field`

### CODE REVIEW

**Review by slorello89 — APPROVED** [review]
LGTM 👍 thank you for submitting this!

**Comment by ahmedisam99** [comment]
@slorello89 Will you be releasing v0.7.3 for this change? It affects my work directly and I don't want to have my version of `Redis.OM`

**Comment by slorello89** [comment]
@ahmedisam99 - I pushed out 0.7.3.

**Comment by ahmedisam99** [comment]
@slorello89 Many thanks 🙏

**Pull request merged**
