### PR TITLE
fixing other stateful queries issue

### LINKED ISSUE #205: The collections state is no longer correct. even when saveState = false when using FirstOrDefaultAsync
Hi @slorello89, 

Would you expect to still receive this error even when saveState is set to false?

```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. 
A concurrent update was performed on this collection and corrupted its state. The collections state is no longer correct.   
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Redis.OM.Modeling.RedisCollectionStateManager.InsertIntoSnapshot(String key, Object value)
   at Redis.OM.Searching.RedisCollection`1.FirstOrDefaultAsync(Expression`1 expression)
```

### PR DESCRIPTION
**Pull request by slorello89**
Fixes #205, adding better exception handling for folks who try enumerating the same redis collection twice. @VagyokC4 - can you check this to make sure this fixes your issue :)

### CODE REVIEW

**Comment by VagyokC4** [comment]
> Fixes #205, adding better exception handling for folks who try enumerating the same redis collection twice. @VagyokC4 - can you check this to make sure this fixes your issue :)

The commit looks good.  Can you drop 0.2.4 to test?

**Comment by VagyokC4** [comment]
@shacharPash @slorello89 Are we able to push this out to nuget real quick?

**Comment by VagyokC4** [comment]
> @VagyokC4 - can you build it from source to check to make sure it totally solves the problem for you? I'm at a conference this week so a bit OOP :)

@slorello89 Hmmm... so it's working, but it's not.  I'm trying to reduce down to a repeatable test... but the initial bug is gone, as I get my data back, however the connection is now dead and all future queried timeout.  Any ideas?

I'll keep testing and update as I know more.

**Comment by VagyokC4** [comment]
@slorello89 Ok, We can close this issue out, as the fix appears to be working.  I will open a new issue as the issue I am seeing I can reproduce in older versions (0.2.1) so this is a completely different / new issue.

**Comment by slorello89** [comment]
@VagyokC4 - that issue you are describing is an older issue with RediSearch (not redis-om-dotnet), where the client was freezing when you went over 10k search results, that issue SHOULD be resolved already.

**Comment by slorello89** [comment]
@VagyokC4 opened a separate issue and confirmed that his 10K search result issue was fixed in a forthcoming version of redis-stack (only applies to RC-7 I think?)

**Review by banker — APPROVED** [review]

**Comment by slorello89** [comment]
Waiting on approvals @rpf3 - ping @shacharPash @chayim

**Review by shacharPash — APPROVED** [review]

**Pull request merged**
