### PR TITLE
fix query predicate bug for NotEqual expression type

### PR DESCRIPTION
**Pull request by mdrakib**

### CODE REVIEW

**Comment by Youbas** [comment]
Any chance we can get this? Looks useful to me!

**Review by slorello89 — CHANGES_REQUESTED** [review]
Hi @mdrakib - first off, thanks for opening this, I'm assuming this is query generation for numeric `!=`? can you add a test to show what it's fixing?

thanks!

**Comment by mdrakib** [comment]
> Hi @mdrakib - first off, thanks for opening this, I'm assuming this is query generation for numeric `!=`? can you add a test to show what it's fixing?
> 
> thanks!

Hi @slorello89 

Thanks for your reply, I have added a test coverage, please review.

**Review by slorello89 — APPROVED** [review]
LGTM 👍 thank you!

**Pull request merged**
