### PR TITLE
Add Basic Matching Queries Example

### LINKED ISSUE #219: Hacktoberfest Examples: Basic Matching Queries (strings, numerics, enums, booleans)
An example with some basic matching queries for strings, numerics, enums, and booleans, in top-level objects and within embedded documents.

See #217 before getting started.

If you’d like to work on this please mention me [@slorello89](https://github.com/slorello89) or [@SuzeShardlow](https://github.com/SuzeShardlow) in a comment and we’ll assign this issue to you.
This is part of our participation in Hacktoberfest 2022. Learn how to complete this issue here: https://redis.io/community/hacktoberfest/
Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest [channel](https://discord.com/channels/697882427875393627/895802042797395989)

### PR DESCRIPTION
**Pull request by berviantoleo**
Closes #219 

Discord handle: bervianto.leo#3385

### CODE REVIEW

**Comment by rtynski** [comment]
Change  Directory name to PascalCase (helpers -> Helpers,  models -> Models).

**Comment by berviantoleo** [comment]
> Change Directory name to PascalCase (helpers -> Helpers, models -> Models). Add new lines at the end of file.

Thank you for your review. I've updated the PR.

**Comment by SuzeShardlow** [comment]
Hi @berviantoleo, thanks for your PR! @slorello89 will be the reviewer.

**Review by slorello89 — APPROVED** [review]
LGTM 👍 Thanks for the contribution @berviantoleo - happy 🎃 hacktoberfest! 🎃

**Comment by berviantoleo** [comment]
> LGTM 👍 Thanks for the contribution @berviantoleo - happy 🎃 hacktoberfest! 🎃 

Thank you. 🙂

**Comment by SuzeShardlow** [comment]
> Closes #219
> 
> Discord handle: bervianto.leo#3385

Thanks @berviantoleo, I've given you the `Hacktoberfest 2022` role in our Discord server :)

**Comment by berviantoleo** [comment]
> > Closes #219
> > Discord handle: bervianto.leo#3385
> 
> Thanks @berviantoleo, I've given you the `Hacktoberfest 2022` role in our Discord server :)

Thank you.

**Pull request merged**
