### PR TITLE
feature: autocomplete suggestions 

### PR DESCRIPTION
**Pull request by Jeevananthan-23**
Adds auto-suggestion #248 feature where you can get the completion suggestions by adding the suggestion string to Redis.
**Auto-Suggestion commands support:**
1. [`FT.SUGADD`](https://redis.io/commands/?group=suggestion) - Adds a suggestion string to an auto-complete dictionary.
2.  [`FT.SUGGET`](https://redis.io/commands/?group=suggestion) - Get a list of suggestions for a string.
3.  [`FT.SUGDEL`](https://redis.io/commands/?group=suggestion) - Deletes a suggestion string from an auto-complete dictionary.
4.  [`FT.SUGLEN`](https://redis.io/commands/?group=suggestion) - Returns the size of an auto-completion dictionary

### CODE REVIEW

**Comment by Jeevananthan-23** [comment]
Hi @slorello89, please provide suggestions for changes on the above PR.

**Comment by zulander1** [comment]
@Jeevananthan-23 is this branch stale ?

**Comment by Jeevananthan-23** [comment]
@zulander1, We can work on it.

**Comment by zulander1** [comment]
> @zulander1, We can work on it.

Yes, What is missing?

**Pull request closed without merging**
