### PR TITLE
Add Wrapper for FT.INFO to get index information

### PR DESCRIPTION
**Pull request by frostshoxx**
Add `GetIndexInfo(typeof(ClassName))` and `GetIndexInfoAsync(typeof(ClassName))`  to `RedisSearchCommand.cs`. It will return `RedisIndexInfo`, which is a mapping class for the `RedisReply` from `FT.INFO idx command`.

### CODE REVIEW

**Review by slorello89 — CHANGES_REQUESTED** [review]
Hey @frostshoxx - looks pretty good - win the tests though, can you please validate that it actually parsers the info as expected?

**Comment by frostshoxx** [comment]
> Hey @frostshoxx - looks pretty good - win the tests though, can you please validate that it actually parsers the info as expected?

I added some more assertions into the test. Please let me know if that works. Thank you!

**Review by slorello89 — APPROVED** [review]
LGTM 👍

**Comment by frostshoxx** [comment]
#179 this PR is tied to this issue btw.

**Pull request merged**
